version: 2
jobs:
  build:
    working_directory: ~/arcane_bet
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          DATABASE_HOST:          localhost
          APP_NAME:               arcane_bet
          DATABASE_USERNAME:      ubuntu
          RAILS_ENV:              test
          CIRCLE_CI_RUBY_VERSION: 2.5.3
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB:   arcane_bet_test

    steps:
      - checkout

      - run:
          name:    Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Install Selenium dependencies
          command: sudo apt install -y libnss3

      - restore_cache:
          name: Restore bundle
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - restore_cache:
          name: Restore node modules
          keys:
            - v1-packs-{{ checksum "yarn.lock" }}
            - v1-packs-

      - run:
          name:    Setup application
          command: bin/setup

      - save_cache:
          name: Store bundle cache
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

      - save_cache:
          name: Store node modules
          key: v1-packs-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name:    Brakeman
          command: bundle exec brakeman --no-progress --separate-models --exit-on-warn

      - run:
          name:    Rubocop
          command: bundle exec rubocop

      - run:
          name:    Split tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

      - run:
          name:    Run Unit/Integration tests
          command: bundle exec rspec --exclude-pattern "spec/features/**/*"

      - run:
          name:    Run Acceptance tests
          command: bundle exec rspec spec/features

      # Circle CI Reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path:        /tmp/test-results
          destination: test-results
