default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch('DATABASE_HOST', 'postgres') %>
  port:     <%= ENV.fetch('DATABASE_PORT', 5432) %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'arcane_test').dup.concat('_development') } %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'arcane_test').dup.concat('_production') } %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'application') }.dup.concat('_test')}#{ENV['TEST_ENV_NUMBER']}" %>heroku